### PR TITLE
Updated small typo on homework_6_starter

### PR DESCRIPTION
**Pull request by AfroGrit**
chore: changed eta first to 0.1 and then to 0.01 to eta first to 0.1 and then to 0.3. to match assignment question

### CODE REVIEW

**Comment by alexeygrigorev** [comment]
@ThinamXx please review

**Comment by ThinamXx** [comment]
Can you change to "change eta from 0.3 to 0.1" as mentioned in the assignment instructions?

**Review by ThinamXx — CHANGES_REQUESTED** [review]
Please change as mentioned in the instructions.

**Comment by alexeygrigorev** [comment]
What should be changed? I'm not sure I understood

**Comment by ThinamXx** [comment]
It's the markdown instructions in the notebook. If you want, I can change it myself but let's wait for Afro.

**Review by ThinamXx — APPROVED** [review]

**Comment by ThinamXx** [comment]
Alexey! Can you merge it? I have updated the typo.

**Comment by AfroGrit** [comment]
thanks

**Comment by alexeygrigorev** [comment]
Thanks!

**Pull request merged**
