### PR TITLE
add notes to section 02-regression README 

### PR DESCRIPTION
**Pull request by wgb-10**
Added my notes to the readme and fixed some typos in some of the units.

### CODE REVIEW

**Comment by alexeygrigorev** [comment]
Can you please resolve the conflict? for some reasons I can't do it from the web interface

**Comment by wgb-10** [comment]
> Can you please resolve the conflict? for some reasons I can't do it from the web interface

Sure, will do.

**Comment by wgb-10** [comment]
Deleted branch by mistake. Re-opening PR.

**Comment by wgb-10** [comment]
For some reason when I resolve the conflict, I get the error: "This page is out of date. Start over" and when I try again, I keep getting the error.

image

**Comment by wgb-10** [comment]
It should be fine now

**Comment by alexeygrigorev** [comment]
Thank you! Squashed all the commits, so please rebase your fork for next PRs

**Comment by wgb-10** [comment]
Alright, thank you. Was a bit of a nightmare since I never dealt with merge conflicts like this before. But I learnt something new.

**Pull request merged**
