### PR TITLE
added code

### PR DESCRIPTION
**Pull request by timliubentoml**

### CODE REVIEW

**Comment by alexeygrigorev** [comment]
Thanks! can you also add the notebook? (maybe first remove the non-relevant stuff like decision trees, tuning, etc - just leave the part where we train the final xgboost model)

**Comment by alexeygrigorev** [comment]
also can you please move it to the `code/` folder within the module folder? thanks!

**Comment by timliubentoml** [comment]
I moved the code to the code/ folder. But what do you mean about the notebook? It's the exact same as the module 6 notebook. Should I copy that one over?

**Comment by timliubentoml** [comment]
by the way, do you need the answers to the homework? Or you got them already?

**Comment by alexeygrigorev** [comment]
Students were asking for the notebook that you were using in the videos. But i know that it's just a few extra lines on top of the notebook in module 6

**Pull request merged**
