### PR TITLE
Update 06-environment.md

### PR DESCRIPTION
**Pull request by nindate**
Added method to open Jupyter notebook in Kaggle

### CODE REVIEW

**Comment by alexeygrigorev** [comment]
For the image, you can create the "images" folder and put it there

**Comment by alexeygrigorev** [comment]
Looks great! For images, I was thinking of having a separate `images` folder for each session. Maybe you could move the folder to `01-intro`? Then you'll be able to refer to images without `../`

**Comment by nindate** [comment]
moved images to 01-intro and updated the 06-environment.md to refer to those

**Comment by alexeygrigorev** [comment]
Thank you for your contribution!

**Pull request merged**
