### PR TITLE
updated notations

### PR DESCRIPTION
**Pull request by jeswanthmukesh20**

### CODE REVIEW

**Comment by alexeygrigorev** [comment]
Does github render latex?

**Comment by jeswanthmukesh20** [comment]
sorry, not rendered!!

I'll fix that

**Comment by alexeygrigorev** [comment]
But before you do this - I'm not sure if it's actually a good idea to add something that wasn't covered in the video  - I'm not sure this notation was used there. I'm afraid it might confuse some people who're not used to math

**Comment by jeswanthmukesh20** [comment]
okay

**Pull request closed without merging**
