### PR TITLE
Numpy Cheat sheet in Additional links

### PR DESCRIPTION
**Pull request by aurcode**

### CODE REVIEW

**Comment by alexeygrigorev** [comment]
Can you move it to links? "Notes" is for notes based on the lesson

**Comment by alexeygrigorev** [comment]
Or maybe even create a section "Additional links" and put it there

**Comment by aurcode** [comment]
I create a section "Additional links" and put numpy cheat sheet there

**Comment by alexeygrigorev** [comment]
Thanks for your contribution!

**Pull request merged**
